Feature/cafe list
Sprokopyak/angularMaterial pull request #8
Opened 2018-06-18 13:13 UTC by Sprokopyak

Add cafe list

2018-06-20 20:45 UTC, GAndriyS requested changes

2018-06-20 20:45 UTC, GAndriyS commented on src/app/cafe/add-cafe/add-cafe.component.ts
> +  @ViewChild('search') public searchElementRef: ElementRef;
no need to use public keyword

2018-06-20 20:45 UTC, GAndriyS commented on src/app/cafe/add-cafe/add-cafe.component.ts
> +    public imageUploadService: ImageUploadService,
no need to use public keyword

2018-06-20 20:45 UTC, GAndriyS commented on src/app/cafe/add-cafe/add-cafe.component.ts
> +  removeGalleryImg(img): void {
decide to specify or don't :void, be consistent across application

2018-06-20 20:45 UTC, GAndriyS commented on src/app/cafe/add-cafe/add-cafe.component.ts
> +    let index = this.tables.indexOf(table);
use const as often as possible

2018-06-20 20:45 UTC, GAndriyS commented on src/app/core/cafe-service/cafe.service.ts
> +  cafeRef: AngularFirestoreCollection<Cafe> = this._afs.collection("cafes");
inconsistent double quotes

2018-06-20 20:45 UTC, GAndriyS commented on src/app/core/core.module.ts
> +import { CafeService } from "./cafe-service/cafe.service";
again inconsistent ' / "

2018-06-20 20:45 UTC, GAndriyS commented on src/app/core/image-upload/image-upload.service.ts
> +  thumbnailStorageUrl = 'https://firebasestorage.googleapis.com/v0/b/easy-book-2fcf6.appspot.com/o/';
group private and public props

2018-06-20 20:45 UTC, GAndriyS commented on src/app/core/infinity-scroll/infinity-scroll.service.ts
> +  private query: QueryConfig;
missed underscore

2018-06-20 20:45 UTC, GAndriyS commented on src/app/core/infinity-scroll/infinity-scroll.service.ts
> +    .pipe(
optimize code formatting here

2018-06-20 20:45 UTC, GAndriyS commented on src/app/core/infinity-scroll/infinity-scroll.service.ts
> +console.log(col);
missed console.log

2018-06-20 20:45 UTC, GAndriyS commented on src/app/core/infinity-scroll/infinity-scroll.service.ts
> +      tap(arr => {
code formatting

2018-06-20 20:45 UTC, GAndriyS commented on src/app/core/infinity-scroll/infinity-scroll.service.ts
> +        console.log(arr);
missed console.log

2018-06-20 20:45 UTC, GAndriyS commented on src/app/core/infinity-scroll/infinity-scroll.service.ts
> +    console.log(val);
????

2018-06-20 20:45 UTC, GAndriyS commented on src/app/directives/same-height.directive.ts
> +  selector: "[samehHeight]"
" again

2018-06-20 20:45 UTC, GAndriyS commented on src/app/directives/scrollable.directive.ts
> +    } catch (err) {}
no need in try catch if there are no error handling

2018-06-20 20:45 UTC, GAndriyS commented on src/app/home/home.component.ts
> +    private afs: AngularFirestore,
underscore for private props

2018-06-20 20:45 UTC, GAndriyS commented on src/app/home/home.component.ts
> +    public page: InfinityScrollService
no need in public keyword

2018-06-21 10:06 UTC, Sprokopyak commented on src/app/home/home.component.ts
> +    public page: InfinityScrollService
I use this service in html

2018-06-21 10:07 UTC, Sprokopyak commented on src/app/cafe/add-cafe/add-cafe.component.ts
> +    public imageUploadService: ImageUploadService,
I use this service in html

2018-06-21 16:01 UTC, merged